/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as MethodRouteImport } from './routes/method'
import { Route as DeskIndexRouteImport } from './routes/desk/index'
import { Route as DeskDossierRouteImport } from './routes/desk/dossier'
import { Route as DeskNewsRouteImport } from './routes/desk/news'
import { Route as DeskSignalsRouteImport } from './routes/desk/signals'
import { Route as DeskInsightIdRouteImport } from './routes/desk/insight.$id'
import { Route as DeskNewsIdRouteImport } from './routes/desk/news.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskDossierRoute = DeskDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => DeskRoute,
} as any)
const DeskNewsRoute = DeskNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSignalsRoute = DeskSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => DeskRoute,
} as any)
const DeskInsightIdRoute = DeskInsightIdRouteImport.update({
  id: '/insight/$id',
  path: '/insight/$id',
  getParentRoute: () => DeskRoute,
} as any)
const DeskNewsIdRoute = DeskNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeskNewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteWithChildren
  '/method': typeof MethodRoute
  '/desk/dossier': typeof DeskDossierRoute
  '/desk/news': typeof DeskNewsRouteWithChildren
  '/desk/signals': typeof DeskSignalsRoute
  '/desk/': typeof DeskIndexRoute
  '/desk/insight/$id': typeof DeskInsightIdRoute
  '/desk/news/$id': typeof DeskNewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/desk/dossier': typeof DeskDossierRoute
  '/desk/news': typeof DeskNewsRouteWithChildren
  '/desk/signals': typeof DeskSignalsRoute
  '/desk': typeof DeskIndexRoute
  '/desk/insight/$id': typeof DeskInsightIdRoute
  '/desk/news/$id': typeof DeskNewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteWithChildren
  '/method': typeof MethodRoute
  '/desk/dossier': typeof DeskDossierRoute
  '/desk/news': typeof DeskNewsRouteWithChildren
  '/desk/signals': typeof DeskSignalsRoute
  '/desk/': typeof DeskIndexRoute
  '/desk/insight/$id': typeof DeskInsightIdRoute
  '/desk/news/$id': typeof DeskNewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/method'
    | '/desk/dossier'
    | '/desk/news'
    | '/desk/signals'
    | '/desk/'
    | '/desk/insight/$id'
    | '/desk/news/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/method'
    | '/desk/dossier'
    | '/desk/news'
    | '/desk/signals'
    | '/desk'
    | '/desk/insight/$id'
    | '/desk/news/$id'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/method'
    | '/desk/dossier'
    | '/desk/news'
    | '/desk/signals'
    | '/desk/'
    | '/desk/insight/$id'
    | '/desk/news/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRouteWithChildren
  MethodRoute: typeof MethodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/dossier': {
      id: '/desk/dossier'
      path: '/dossier'
      fullPath: '/desk/dossier'
      preLoaderRoute: typeof DeskDossierRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/news': {
      id: '/desk/news'
      path: '/news'
      fullPath: '/desk/news'
      preLoaderRoute: typeof DeskNewsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/signals': {
      id: '/desk/signals'
      path: '/signals'
      fullPath: '/desk/signals'
      preLoaderRoute: typeof DeskSignalsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/insight/$id': {
      id: '/desk/insight/$id'
      path: '/insight/$id'
      fullPath: '/desk/insight/$id'
      preLoaderRoute: typeof DeskInsightIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/news/$id': {
      id: '/desk/news/$id'
      path: '/$id'
      fullPath: '/desk/news/$id'
      preLoaderRoute: typeof DeskNewsIdRouteImport
      parentRoute: typeof DeskNewsRoute
    }
  }
}

interface DeskNewsRouteChildren {
  DeskNewsIdRoute: typeof DeskNewsIdRoute
}

const DeskNewsRouteChildren: DeskNewsRouteChildren = {
  DeskNewsIdRoute: DeskNewsIdRoute,
}

const DeskNewsRouteWithChildren = DeskNewsRoute._addFileChildren(
  DeskNewsRouteChildren,
)

interface DeskRouteChildren {
  DeskDossierRoute: typeof DeskDossierRoute
  DeskNewsRoute: typeof DeskNewsRouteWithChildren
  DeskSignalsRoute: typeof DeskSignalsRoute
  DeskIndexRoute: typeof DeskIndexRoute
  DeskInsightIdRoute: typeof DeskInsightIdRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskDossierRoute: DeskDossierRoute,
  DeskNewsRoute: DeskNewsRouteWithChildren,
  DeskSignalsRoute: DeskSignalsRoute,
  DeskIndexRoute: DeskIndexRoute,
  DeskInsightIdRoute: DeskInsightIdRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRouteWithChildren,
  MethodRoute: MethodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
